/* ═══════════════════════════════════════════════════════════════════════════
   Demo films (2.17)
   ───────────────────────────────────────────────────────────────────────────
   One four-second loop — the house colours drifting — for the video block's
   ambient display in the block library, as a WebM and an MP4. Small enough
   to live in code like the demo pictures (8 KB between them), so the
   repository still holds no binary media. Made with ffmpeg's `gradients`
   source; the demo seed and templates write them like any other demo file.
   ═══════════════════════════════════════════════════════════════════════════ */

export type DemoVideo = {
  name: string;
  format: 'webm' | 'mp4';
  width: number;
  height: number;
  durationMs: number;
  alt: string;
  base64: string;
};

const WEBM =
  'GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAnuEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZU' +
  'rmtTrIHYTbuMU6uEElTDZ1OsggEmTbuMU6uEHFO7a1OsggnY7AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmsirXsYMPQkBNgI1M' +
  'YXZmNjIuMTIuMTAyV0GNTGF2ZjYyLjEyLjEwMkSJiECvQAAAAAAAFlSua8muAQAAAAAAAEDXgQFzxYgjpDACP7ISzJyBACK1nIN1' +
  'bmSIgQCGhVZfVlA5g4EBI+ODhAT3kNXgkbCCAUC6gbSagQJVsIRVuYEBElTDZ0CAc3OgY8CAZ8iaRaOHRU5DT0RFUkSHjUxhdmY2' +
  'Mi4xMi4xMDJzc9pjwItjxYgjpDACP7ISzGfIpUWjh0VOQ09ERVJEh5hMYXZjNjIuMjguMTAyIGxpYnZweC12cDlnyKFFo4hEVVJB' +
  'VElPTkSHkzAwOjAwOjA0LjAwMDAwMDAwMAAfQ7Z1SCbngQCjQPqBAACAgkmDQgAT8As2CDgkHBj2AAFgYfV+D+N427AjEdSd/9g9' +
  'REP4YcoAAGc//PnDu6Z56KrwKbnOjpPjrfEPAT1wH5N7DAd9/F/snis6Oi9vePxLQmo3IQeDxZkT+sjXsgkD+Hq27dUal/2BkXxi' +
  'HKEbcUNVCWi5zh1bX2cesSnwzG+cwCCR5CrR2490Z8wst7zzKzwjFFK2Q8H+cHm5yX8Hratry5DwvFqm1vW9BfThUNNYyeDmv1En' +
  'M2qeeFYdHjZJVsEUJW/ThiRWFRK2EleCfAITnr4LfCBaOntxiX/3CFVAKaut3fJYQFC++qnfrHOdbc9EpAAAo5yBAFMAhgBAkhwQ' +
  'WQAAAyAAAFuyPvJy76Q7ljoAo5+BAKcAhgBAkpwQWAAAAyAAAFqS2fEMLjryHLKf5vQwo6GBAPoAhgBAkhwQWQAAAyAAAFu3Y2ub' +
  '/Uvx/vhE+R6sdgCjpYEBTQCGAECSnBBWoAADYAAAWVYaNz6PlBNAXmzQ2xQSG5ahwACjoYEBoQCGAECSHBBZAAADIAAAW7JVHmKt' +
  'rKsDKjpvMTl5AKOggQH0AIYAQJKcCFgAAANgAABaks828GyPUqkOTUI5f+CjqoECRwCGAECSHAhZAAADYAAAW7MGIo6UhFlBHKu0' +
  '4FF+KlrqMu9BLvHAAKO9gQKbAIYAQJKMCFRgAAZgGECuigBcH62rYuBjRe1HqSC7a9QL2xv1VjkwsCXnSbgFsZ7crWMmQ/KgY/PA' +
  'AKOegQLuAIYAQJIMEFkAAAMgAABapZPKi6E+UyjFW0qgo6+BA0EAhgDAkvAhUYAADCAAAFjafLUJDcZLX6GzdPVPJCluGF04JFQY' +
  'wegclEljAKOhgQOVAIYAQJIMEFkAAAMgAABaj/jdQs1xjpcK0D9JJT+wo6eBA+gAhgBAkowQVqAAAyAAAFqlt5pmoQurK0RoxnEb' +
  'YgWbS1rkZQCjnIEEOwCGAECSDAhZAAADIAAAWkuT2I0bXBQnvkCjqIEEjwCGAECSjBBYAAADIAAAWqXCvYR6nzNdTnLDK9mZwxzh' +
  'KIB1boCjp4EE4gCGAECSDAhZAAADYAAAXBGMrNZUkk3lx9SHnIpmNn6/xQl9PKOxgQU1AIYAQJKMCFRgAANgAABcIog4p+pqcZAi' +
  '42x6Q3N31EBsYiSFUpA7Gj9PI6taAKOfgQWJAIYAQJIMEFkAAAMgAABaj/tq0uSacr1VJNyMAKOigQXcAIYAQJKMCFgAAAMgAABb' +
  'vBe8Svgz06FK9I790T+KAKOggQYvAIYAQJIMEFkAAAMgAABakTkI8pMOqPokDa5IhPijtoEGgwCGAMCSnBBUYAADYAAAX/IOwoKz' +
  'ARm+DIFgKWVB2md51sAKYQWRMgRO0eTVrU4SdY0cAKOdgQbWAIYAQJIMCFkAAAMgAABbV5zw5GKnSJABMISjooEHKQCGAECSjAhY' +
  'AAADIAAAW+HucP2POPK3VmhPu9kowACjo4EHfQCGAECSDBBZAAADIAAAWqXCOjSzvgFwimDi1bOeekcAo7uBB9AAhgBAkowIVGAA' +
  'A2AAAFxCKPy2Ky1vm1JiTqmbUSm94bYzLO13ppdS+4vZ8vpKN4jHagfUFnjAAKOdgQgjAIYAQJIMCFkAAAMgAABasT8KNB/TlheA' +
  'YCCjn4EIdwCGAECSjAhYAAADYAAAW7ZpWiG4Al7neW4i4KCjpIEIygCGAECSDAhZAAADYAAAWPCwoyMcy8T9UfVqvZ7+/qoFgKOs' +
  'gQkdAIYAQJKMEFagAANgAABcStLCC5d+vQtuyX4BU9ZtBuqvOLV958/rwhCjn4EJcQCGAECSDAxZAAADIAAAYJ7PM0opRG2b6XKt' +
  '/SCjtIEJxACGAMCSnAxUYAADYAAAW+jxJOuvLrwvkpEaERS4C0oOl9n/000pn7uHK4ynH2DD7rijm4EKFwCGAECSDAxZAAADIAAA' +
  'YFlT/HZfCfdLqKO5gQprAIYAQJKMFFRgAANgAABYS57xnbZWywAIp+7PgTPdnRBQGE4DHPWDSbcQ+ZgB2RDJD2GK8rygo5yBCr4A' +
  'hgBAkgwMWQAAAyAAAFq0C6Azz+5vfQGoo6aBCxEAhgBAkowQWAAAA2AAAFw0M8G0s1UNRHiZjFkYjcWnaf7JAKOggQtlAIYAQJIM' +
  'CFkAAAMgAABf7bKpbTMP3uPjbdVG/ICjroELuACGAECSjBBWoAADYAAAVOkZQOMSpfzjd2HeYbWUBtxoALevgoybM10WwACjnYEM' +
  'CwCGAECSDAxZAAADIAAAW+GwVKCO0nNBrJBAo6KBDF8AhgBAkowMWAAAA2AAAFw0No1PtPrMF4KmIxDkbi9wo52BDLIAhgBAkgwI' +
  'WQAAAyAAAFqxV8cYzn9T7u6mAKOkgQ0FAIYAwJKcCFRgAAMgAABcNHT7y76RipuRXV/4wiqre8gAo5mBDVkAhgBAkgwIWQAAAyAA' +
  'AFqwuFRfxM8Ao6eBDawAhgBAkowIWAAAA2AAAFufgbElwMgjyOyS7aNqEaFJbjD5RXijnIEN/wCGAECSDAhZAAADIAAAYJ3nnQtZ' +
  'IQRXX+CjtIEOUwCGAECSjAhWoAADYAAAYAfJat2RpmDh5BOKioMgwuicXCkTw6+yCug3ZPK+2sRsIoCjnoEOpgCGAECSDBBZAAAD' +
  'IAAAWrGNQg12pX6I/v0EAKOlgQ75AIYAQJKMCFgAAANgAAANqvfJvtH16r/biHAqd5t2sEdLGKOkgQ9NAIYAQJIMCFkAAAMgAABg' +
  'Zgn6EJmw3KMvtr2UZy+Gc1EgHFO7a5G7j7OBALeK94EB8YIBrPCBAw==';

const MP4 =
  'AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAT+bW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAD6AAAQAAAQAA' +
  'AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAA' +
  'BCh0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAD6AAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAA' +
  'AAAAAAAAAAAAAABAAAAAAUAAAAC0AAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAA+gAAAIAAABAAAAAAOgbWRpYQAAACBtZGhk' +
  'AAAAAAAAAAAAAAAAAAAwAAAAwABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAADS21p' +
  'bmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAwtzdGJsAAAAw3N0c2QA' +
  'AAAAAAAAAQAAALNhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAUAAtABIAAAASAAAAAAAAAABFUxhdmM2Mi4yOC4xMDIgbGli' +
  'eDI2NAAAAAAAAAAAAAAAGP//AAAAOWF2Y0MBZAAV/+EAG2dkABWscgRBQZ+fARAAAAMAEAAAAwGA8WLYRgEAB2joQ4ISyLD9+PgA' +
  'AAAAEHBhc3AAAAABAAAAAQAAABRidHJ0AAAAAAAAIHoAAAAAAAAAGHN0dHMAAAAAAAAAAQAAADAAAAQAAAAAFHN0c3MAAAAAAAAA' +
  'AQAAAAEAAAEQY3R0cwAAAAAAAAAgAAAAAgAACAAAAAABAAAUAAAAAAEAAAgAAAAAAQAAAAAAAAABAAAEAAAAAAEAACAAAAAAAQAA' +
  'DAAAAAACAAAAAAAAAAMAAAQAAAAAAQAAHAAAAAABAAAMAAAAAAIAAAAAAAAAAgAABAAAAAABAAAkAAAAAAEAABAAAAAAAwAAAAAA' +
  'AAADAAAEAAAAAAEAAAgAAAAAAQAAEAAAAAACAAAEAAAAAAEAACAAAAAAAQAADAAAAAACAAAAAAAAAAMAAAQAAAAAAQAAGAAAAAAB' +
  'AAAIAAAAAAEAAAAAAAAAAgAABAAAAAABAAAYAAAAAAEAAAgAAAAAAQAAAAAAAAACAAAEAAAAABxzdHNjAAAAAAAAAAEAAAABAAAA' +
  'MAAAAAEAAADUc3RzegAAAAAAAAAAAAAAMAAAA8YAAACbAAAAzAAAACkAAAA5AAAAIAAAAQYAAAA2AAAAPgAAADMAAAAUAAAAGwAA' +
  'ABkAAADNAAAAQgAAABUAAAAZAAAAFQAAACoAAADAAAAAVgAAACgAAAAzAAAAHAAAABoAAAAhAAAAIwAAAI0AAACcAAAAHAAAACEA' +
  'AADDAAAAPAAAABgAAAAaAAAAFAAAACIAAAAYAAAAswAAACgAAAAmAAAAEQAAABEAAAC0AAAAJgAAACQAAAAZAAAAEwAAABRzdGNv' +
  'AAAAAAAAAAEAAAUuAAAAYnVkdGEAAABabWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAtaWxzdAAA' +
  'ACWpdG9vAAAAHWRhdGEAAAABAAAAAExhdmY2Mi4xMi4xMDIAAAAIZnJlZQAAEEVtZGF0AAACsAYF//+s3EXpvebZSLeWLNgg2SPu' +
  '73gyNjQgLSBjb3JlIDE2NSByMzIyMiBiMzU2MDVhIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAy' +
  'NSAtIGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTE2IGRlYmxvY2s9MTow' +
  'OjAgYW5hbHlzZT0weDM6MHgxMzMgbWU9dW1oIHN1Ym1lPTEwIHBzeT0xIHBzeV9yZD0xLjAwOjAuMDAgbWl4ZWRfcmVmPTEgbWVf' +
  'cmFuZ2U9MjQgY2hyb21hX21lPTEgdHJlbGxpcz0yIDh4OGRjdD0xIGNxbT0wIGRlYWR6b25lPTIxLDExIGZhc3RfcHNraXA9MSBj' +
  'aHJvbWFfcXBfb2Zmc2V0PS0yIHRocmVhZHM9NiBsb29rYWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNp' +
  'bWF0ZT0xIGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTggYl9weXJhbWlk' +
  'PTIgYl9hZGFwdD0yIGJfYmlhcz0wIGRpcmVjdD0zIHdlaWdodGI9MSBvcGVuX2dvcD0wIHdlaWdodHA9MiBrZXlpbnQ9MjUwIGtl' +
  'eWludF9taW49MTIgc2NlbmVjdXQ9NDAgaW50cmFfcmVmcmVzaD0wIHJjX2xvb2thaGVhZD02MCByYz1jcmYgbWJ0cmVlPTEgY3Jm' +
  'PTM0LjAgcWNvbXA9MC42MCBxcG1pbj0wIHFwbWF4PTY5IHFwc3RlcD00IGlwX3JhdGlvPTEuNDAgYXE9MToxLjAwAIAAAAEOZYiB' +
  'ABf//m5vXUCMITBlCrLGKFnqRtdUYPKkFIVzA8R75eVTLHCMuvyI9S4eR+bIC81XTKoF2hxpNWUeGojwXkWsu5meZ7YA68rW+why' +
  'U0N1YnaQpRYdwgbU60goOJdAeHjpNs5tRvGwXfKvJ3/kRX2S1u6Gvqz4DgHmf4BwMIkcBc0wQx4XynJFyPQEYw1zZDDJiivmBL+L' +
  'DuHxP0od7iwB6SJm3WKNgLiLwuswqTKsW3yprrQLNmgbUikFzIUz83jr2ziFMorR/FmKAnrg3j3FSAN6akfSsdy6kstS6ekQnFPX' +
  '9vmAHsFcXHzNWPuUd4FVhn3IVnkVmMRVPs0RLz9gZro+M+X8HQ6vw0jBAAAAl0GaCC2L/9Sbq6ARQAmUGiEIxUBKSSiixf3+PKqf' +
  'Wp07WhYrDnERREA8pgJNWfT0MdqdojH1butk1C8bIlqSIxg8Ii5YW5QLKne2MjAtBecVNFm1wmxnOtg/FfKOzVGpemuV+G7FS0Mq' +
  'JDciELhHulkyGcMNJUqZe1XmdZskDL3AknwsI1iSMAGAhniUv31Z7LWaMLaDeLgAAADIQZoQq/AgZMphf/wIfuOXhNs36sxuI0bk' +
  'mre9AAPw9q+K/O3MxNLmfONzZoAWpGMrBmuuhfuOX3JTEtYSDTHMHRTIeL4LWWfkMrSuUOvmLAuofLDu5a3TPa7xYAjWD2xkTO6t' +
  'tN25Upy3dymZKUbH239Id6VEJrSiQpLh1SNSQBXpN/s5j8hWStccQwr0d67VvATM/wKcxU0Jo3A0GHL8g7cA6zdxAEr3oQtpccFH' +
  'OfZhwOkqZvr2Rm252Lt7pwF+ZaptLKjUIX0AAAAlQZ4YZUX/dsXYoQW8rMuMwAqjw+18KajXA7kO7qawqiYHgxk1xQAAADUBniBF' +
  'Iv/VpP9pR9U405oDn0rv13nLsrsGU4d/6AV17ODjgKTNz1iDS/K8HK6LOevG2dFcEQAAABwBniCNy/94w5xrYmrFQfs3UKBly6nU' +
  'tfegrOttAAABAkGaIYl1AgLWTKYBf/6YQHV7//1idR9HMDD2A+C2fsaKXWIk0SjTySBoCWtuM43nFljIOcrDktjoO20XQbhsqqEl' +
  '2Fdf9obYWibdcSZ/vL0CQ90mh/TzmovRvN6Fz+Jove5PZxorzbAL/prd9nYmJOCoiuK+zeiZUPCPnK8jcl4I5bUgiJ2L3T/MxHF+' +
  '5lwQWLcNkZUXXIKrN6y/p7Y+0MrW3PQKVOP/FIXomkO8BztsoYlyPUcoIqbMBO1kxNZC2Gr1hgVDKTtnXLcIRBNzYol4zPQvxC1c' +
  'Fw9gx/eH2vZNSTO/R2IKEdi09JeDGj9H9VhNzS+fdV3YU0/2dE0spynVlQAAADJBnikEkS9ulaDgLBPmib+MKYuM0zUY4AEI61hf' +
  'XMmtsqwiYv6fvhghHy4WmM/7D+n+AQAAADoBnjDEiL+DeqlThVlPG0lapmsIB+xd6A10VwfweYyKZfL1LpKzi9D+5+64s+EDR+nX' +
  'X+Fvoxp3eS7wAAAALwGeMOSIv4N4+hFKgngdbKooAXDKvGzCefCK4DEDSD+gLxjFx715WJgdgBQmMufFAAAAEAGeMSyy/4rMQ5Y4' +
  'zOnABu0AAAAXAZ4xTLL/QNvoZ/2lkThBIj5Ll84AJGYAAAAVAZ4xbLL/QNvoWeQ3Eb7R+oYOdhVbAAAAyUGaMkn1AgLa1kymABE/' +
  '3T7uJ9JadlzL+I0wLc9IrD4Oo2kX+YcJ9DszM2a3aPMwhGJ6C3CC8R7aZPs/ZO+gexpnCQfFgmV1wijv3aWTLLRwYOdlmiGCZSML' +
  'Bd59JcGoO14kGowmb9WG88PWBJgOXZyeVoqTKnrUqfDBsekXUzYUP+EpdOZdMwF69rROxqxjuRhVpRL1Drhvim6B0YvGImEMh2S1' +
  'tvgEjlijMB7qybS2yQ2822StvTEo55Z9Cn1JPbkPPChebstEXQAAAD5Bnjns0X+mv2wofQjuDu1GzmF/oXJjhKMjmFwyZcfBKSIc' +
  '0XOXcEp7ZdpF+gM/EhtPJVTNFba2DfD6KfhowQAAABEBnkGsyL8Vl0aZbXWp0orx5wAAABUBnkHMyL9zUImRleKxrxvmpIzGyj8A' +
  'AAARAZ5CDPL/HqpK54IviJ16uhAAAAAmAZ5CLPL/8DWUgWRAe5xBYDj+5+jSHblKFr/xxCmfWHwMaMvbgFEAAAC8QZpDSJ1AgLa2' +
  'tZMpgABDP8BjcGRwfcm2XiEAl7wK6SzYqk531Lu8Aa+uV/yfiVfgQn5CmGeoUXW3DVCptf2l3KdvI7CeaqW9Ow5SJSKf5wghWDtB' +
  'c+0fG6gCS4H0PTCgehHzahqawPu1Dg82JA9R9M+FhUBBTFI21/gsOhgi4IuBycggPgRUno61NikUvVPLIFemF5UymD3C3ixBBtip' +
  'qo57b9kzsTIMPe4pRhkynCvFAmjZQbYkZfiqQWQAAABSQZ5KzERDv/TyGeT7uT11dPnf+ghRRPvScD8FVV9F72u36xAJ5p+aJa5x' +
  '40nKjjFzKN7j2sl3g1+3t/Va3Dg0kmZhohqT290UMSzMPiQ7UpYZQgAAACQBnlJsQiL/6iVmimhS7DwmaELqIkGmoNLrRkiJB8Aa' +
  '4c58kBEAAAAvAZ5SjEIhn+DC5PIlAePbr3fVbBxHCgApisV8yEVriJIVq63Kw4fxzVUXzYl9s3gAAAAYAZ5SrEIhn+DMdQcLQwtC' +
  'i42vyS0R9CPhAAAAFgGeUuxMhn8xD4xSaGTocR9OwA8pA8EAAAAdAZ5TDEyGfzCkLqbsD1U/e8G/MKGi1kFO5/gPqyQAAAAfAZ5T' +
  'LEyGf8Pu5qoCc85PKD7mrzU0tLAF6mmIQx6VsQAAAIlBmlNovUCAtra2tZMpgAAEN/+z+nQ5mMUCRHhWnVw6nwAAAwJHpyYcsSeC' +
  'z1Sx7GWCQPfem9X3EIU1i63F8fCZO1nhuHA/wf973KCPkPkD0HlQIecJRfwSwLYa4PMloZZhHSTsLIK8y9+eCwANyVIaN4xToq8R' +
  'xRu1lSgpyO0T1Kmbn8OOOyccQgAAAJhBmlvIzwIFLa2trWTKYAAAQ7/ZSSgn2VYP/CNHWuFgAXhAT98Av8WGAoF3sGykxqTvXUjQ' +
  'eUgkvj63cnXhJWg4tMOE+pXwX1QxC1KllGDOKyuFHt81tzlRmWOk8xsD8jeKSn8GHZT01N2oPUvd1lkBrlDGOj8DXMvoE80+NFng' +
  'myI9FQqftXroTB/P2EbUBS3dbGbPDlXsxQAAABhBnmOMXEN/CNg6uY84mCx3oP66QUVw3YEAAAAdAZ5rrGSGfxGnOVg1BFFs168U' +
  '4vMXUsMo8tiUPMAAAAC/QZpsqO1AgLVLa2trWTKYAAADAQ7/5Alg+70N7ngfuJHyqhET52bAD0kXY5/8vBP0T5BfcvEgc7nEsrXb' +
  'Y1VwfKmZWYYcWZE+7W0sw887gT2E8QBpy4ww/0+PBFuTipKz/9mXRRalhHdUhGDhkj522CBl+Uo1sxfQyAyYlevndn47uLA6NvUX' +
  'MHwhuSdZN/i9rrOUN4LFqzTaBv7glWuHfMT8LVarF2acwuMGDkFy+9i/YkUSEJrkNyfa/Lg6aMAAAAA4QZ50LGxDv6/iex89M59Y' +
  'S681+NfOWulXB+DDrPGeCsBP2BC36/mhUHGxmPq2CwpNcysJdXZ9UIEAAAAUAZ577GohnxCU8BKKhIjeHOSGESUAAAAWAZ58DGoh' +
  'n6wSMKK6r4wyXjV+ADcB0QAAABABnnxMdIZ/KkfqN/L6a2eIAAAAHgGefGx0hn8qR+o5ghckeF2DnjslzJx6HgeDfdEkaQAAABQB' +
  'nnyMdIZ/CZifzZcilOiinUrRgQAAAK9Bmn1GoEBbWqW1tbWsmUwAAAMACG//paF4YdughrfVal1+0gfc7J0yYJrYQoGqAcWrnb2Q' +
  'n/aeQWWjQQ+s4Qvmbw7njVCwOA2Wmc3xwy9k0XZ79zp+tGhlTURuqCgWsjBvEiN9S2ceeLIwOmNxRKVByzUeC6V2TFFvZkIwq3fx' +
  'jBpQ7+Nhl4PzG4s368Bcma8KhhW6ZuWTawIejrFDJ29wx8ngxqgVNjq7lzYNlr45AAAAJEGehOx8oIIfh38hOQvkLR0pboHsIMEq' +
  'XMdfl4JtDdxFETwCKwAAACIBnozMaiGfZiOJfi0DuPKTMih1CmYMBGIRHzEXjmYv6m9AAAAADQGejQx0hn8QogSXUTsAAAANAZ6N' +
  'LHSGfxCh7WM8QQAAALBBmo3moEBbW1qltbW1JlMAAAMAAhn/JRztL1jsa2BGF2DVoKssAkJhYNZ7Ou2yzWotHLjSMfgaFvGS7Seq' +
  'CcDfDKYgPGTws1KQ2eV9+4iMZKWCh5S9MMatJF76dIRoVS4mQx85OPafCth0+mG+9ImOSLpdQzySJ6+58Pwc0rJRflzRaZ8tFY38' +
  'kbHaF807zS9avYXAtlAWgHUvetF2mtTGjQ/3xHP5EnCnW2kr6WLMOgAAACJBnpWMfKHoIYd/Hsnwdb5ze96ousEL06vtCo/5hrGt' +
  'weH+AAAAIAGenWxqIZ8k52EWyJenpr6jd2QFPXq09c4eFVHZtZmhAAAAFQGenax0hn+UbkUrIvZQ6mY/NVhyRwAAAA8Bnp3MdIZ/' +
  'NAcgxpD9PWM=';

export const DEMO_VIDEOS: DemoVideo[] = [
  { name: 'ambient-loop', format: 'webm', width: 320, height: 180, durationMs: 4000, alt: 'Colours drifting slowly', base64: WEBM },
  { name: 'ambient-loop', format: 'mp4', width: 320, height: 180, durationMs: 4000, alt: 'Colours drifting slowly', base64: MP4 },
];

export const demoVideoFile = (video: DemoVideo) => `demo/${video.name}.${video.format}`;

/** A demo film's public address — for demo content. */
export const demoVideo = (name: string, format: DemoVideo['format']) => `/media/demo/${name}.${format}`;
