/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * What each self-hosted family is called, what it is for, which scripts it
 * can actually draw, and the licence it travels under.
 */

export type CatalogueRole = 'sans' | 'serif' | 'display' | 'mono';

export type CatalogueEntry = {
  key: string;
  family: string;
  role: CatalogueRole;
  scripts: readonly string[];
  licence: string;
};

export const FONT_CATALOGUE: readonly CatalogueEntry[] = [
  {
    "key": "alegreya",
    "family": "Alegreya",
    "role": "serif",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "arimo",
    "family": "Arimo",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "asap",
    "family": "Asap",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "assistant",
    "family": "Assistant",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "barlow",
    "family": "Barlow",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "bitter",
    "family": "Bitter",
    "role": "serif",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "cabin",
    "family": "Cabin",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "commissioner",
    "family": "Commissioner",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "dmSans",
    "family": "DM Sans",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "dosis",
    "family": "Dosis",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "exo2",
    "family": "Exo 2",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "figtree",
    "family": "Figtree",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "firaSans",
    "family": "Fira Sans",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "heebo",
    "family": "Heebo",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "hind",
    "family": "Hind",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "ibmPlexMono",
    "family": "IBM Plex Mono",
    "role": "mono",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "ibmPlexSans",
    "family": "IBM Plex Sans",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "inconsolata",
    "family": "Inconsolata",
    "role": "mono",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "inter",
    "family": "Inter",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "jetbrainsMono",
    "family": "JetBrains Mono",
    "role": "mono",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "josefinSans",
    "family": "Josefin Sans",
    "role": "display",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "karla",
    "family": "Karla",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "lato",
    "family": "Lato",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "libreBaskerville",
    "family": "Libre Baskerville",
    "role": "serif",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "lora",
    "family": "Lora",
    "role": "serif",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "manrope",
    "family": "Manrope",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "merriweather",
    "family": "Merriweather",
    "role": "serif",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "montserrat",
    "family": "Montserrat",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "mulish",
    "family": "Mulish",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "notoSans",
    "family": "Noto Sans",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "notoSansArmenian",
    "family": "Noto Sans Armenian",
    "role": "sans",
    "scripts": [
      "armenian",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "notoSerif",
    "family": "Noto Serif",
    "role": "serif",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "notoSerifArmenian",
    "family": "Noto Serif Armenian",
    "role": "serif",
    "scripts": [
      "armenian",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "nunito",
    "family": "Nunito",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "nunitoSans",
    "family": "Nunito Sans",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "openSans",
    "family": "Open Sans",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "oswald",
    "family": "Oswald",
    "role": "display",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "outfit",
    "family": "Outfit",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "playfairDisplay",
    "family": "Playfair Display",
    "role": "serif",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "plusJakartaSans",
    "family": "Plus Jakarta Sans",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "poppins",
    "family": "Poppins",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "ptSans",
    "family": "PT Sans",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "ptSerif",
    "family": "PT Serif",
    "role": "serif",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "quicksand",
    "family": "Quicksand",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "raleway",
    "family": "Raleway",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "roboto",
    "family": "Roboto",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "robotoCondensed",
    "family": "Roboto Condensed",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "robotoMono",
    "family": "Roboto Mono",
    "role": "mono",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "rubik",
    "family": "Rubik",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "sourceCodePro",
    "family": "Source Code Pro",
    "role": "mono",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "sourceSans3",
    "family": "Source Sans 3",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "spaceGrotesk",
    "family": "Space Grotesk",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "titilliumWeb",
    "family": "Titillium Web",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  },
  {
    "key": "ubuntu",
    "family": "Ubuntu",
    "role": "sans",
    "scripts": [
      "cyrillic",
      "greek",
      "latin"
    ],
    "licence": "UFL-1.0"
  },
  {
    "key": "workSans",
    "family": "Work Sans",
    "role": "sans",
    "scripts": [
      "latin"
    ],
    "licence": "OFL-1.1"
  }
];
