import { FONT_LABELS, FONT_ROLES, type FontKey } from './theme';
import { FONT_CATALOGUE } from './fontCatalogue';

/* ═══════════════════════════════════════════════════════════════════════════
   Which faces can draw which languages
   ───────────────────────────────────────────────────────────────────────────
   A typeface is a design choice right up to the point where it cannot draw
   the alphabet. Then it is a bug: the browser silently substitutes whatever
   the reader's device has, and an Armenian page ends up in a font nobody
   chose, usually mismatched in weight and colour with the Latin around it.

   The three **brand** faces are Latin-only — measured, not assumed: no
   `@font-face` in `fonts.css` declares a range covering Cyrillic or Armenian.
   The self-hosted Google Fonts catalogue beside them does carry Cyrillic,
   Greek and Armenian, per family, and `fontCatalogue.ts` records exactly
   which — generated by the fetcher from the subsets it actually downloaded,
   so nothing here claims a file that is not on disk.

   That is what makes the warnings honest: the admin can say which face each
   language uses, and the screen says out loud when the chosen one cannot draw
   it. See `docs/fonts.md`.
   ═══════════════════════════════════════════════════════════════════════════ */

export const SCRIPTS = ['latin', 'cyrillic', 'greek', 'armenian', 'arabic', 'hebrew'] as const;
export type Script = (typeof SCRIPTS)[number];

export const SCRIPT_LABELS: Record<Script, string> = {
  latin: 'Latin',
  cyrillic: 'Cyrillic',
  greek: 'Greek',
  armenian: 'Armenian',
  arabic: 'Arabic',
  hebrew: 'Hebrew',
};

/**
 * What each bundled face can actually draw.
 *
 * `system` and `serif` are not bundled — they resolve to whatever the reader's
 * device provides — so they are marked as covering everything. That is not a
 * promise about how it will look, and the admin screen says so: a system font
 * will *render* Armenian, and it will not match the rest of the design.
 */
export const FONT_SCRIPTS: Record<FontKey, readonly Script[]> = {
  display: ['latin'],
  sans: ['latin'],
  mono: ['latin'],
  system: SCRIPTS,
  serif: SCRIPTS,
  /* The catalogue knows what it fetched, because the fetcher recorded the
     subsets it actually downloaded. Nothing here is a claim about a file
     that might not exist. */
  ...Object.fromEntries(FONT_CATALOGUE.map((f) => [f.key, f.scripts as readonly Script[]])),
};

/** Whether a face is one the engine ships, rather than the reader's own. */
export const BUNDLED: Record<FontKey, boolean> = {
  display: true,
  sans: true,
  mono: true,
  system: false,
  serif: false,
  ...Object.fromEntries(FONT_CATALOGUE.map((f) => [f.key, true])),
};

/**
 * The script a language is written in.
 *
 * Only the ones that are not Latin are listed; everything else defaults, which
 * keeps this to the languages where the answer matters.
 */
const SCRIPT_BY_LOCALE: Record<string, Script> = {
  hy: 'armenian',
  ru: 'cyrillic',
  bg: 'cyrillic',
  uk: 'cyrillic',
  sr: 'cyrillic',
  mk: 'cyrillic',
  be: 'cyrillic',
  kk: 'cyrillic',
  ky: 'cyrillic',
  mn: 'cyrillic',
  el: 'greek',
  ar: 'arabic',
  fa: 'arabic',
  ur: 'arabic',
  he: 'hebrew',
};

export function scriptFor(locale: string): Script {
  return SCRIPT_BY_LOCALE[locale.toLowerCase().split('-')[0]!] ?? 'latin';
}

export function covers(font: FontKey, script: Script): boolean {
  return FONT_SCRIPTS[font].includes(script);
}

export type FontWarning = { font: FontKey; script: Script; bundled: boolean };

/**
 * What is wrong with a face for a language, or null when nothing is.
 *
 * Two different problems, and they need different words: a bundled face that
 * cannot draw the alphabet at all, and a system face that can draw it but is
 * not the site's design.
 */
export function fontWarning(font: FontKey, locale: string): FontWarning | null {
  const script = scriptFor(locale);
  if (script === 'latin') return null;
  if (covers(font, script)) {
    return BUNDLED[font] ? null : { font, script, bundled: false };
  }
  return { font, script, bundled: BUNDLED[font] };
}

/** The sentence the admin screen shows for a warning. */
export function warningText(warning: FontWarning, languageName: string): string {
  const script = SCRIPT_LABELS[warning.script];
  if (!warning.bundled) {
    return `${FONT_LABELS[warning.font]} uses whatever the reader's device provides for ${script}, so ${languageName} will not match the rest of the design.`;
  }
  return `${FONT_LABELS[warning.font]} has no ${script} glyphs, so ${languageName} falls back to the reader's own font. Add a ${script} subset for this face, or choose one that has it.`;
}

/**
 * Every face, for a picker — grouped, because fifty in one flat list is not a
 * menu anybody can use. The site's own five come first under their own
 * heading; the rest follow by what they are for.
 */
export const FONT_GROUPS: { label: string; options: { value: FontKey; label: string }[] }[] = (() => {
  const brand = ['display', 'sans', 'mono', 'system', 'serif'];
  const groups: { label: string; options: { value: FontKey; label: string }[] }[] = [
    { label: 'This site', options: brand.map((value) => ({ value, label: FONT_LABELS[value]! })) },
  ];

  const byRole: Record<string, { value: FontKey; label: string }[]> = {};
  for (const font of FONT_CATALOGUE) {
    (byRole[font.role] ??= []).push({ value: font.key, label: font.family });
  }
  for (const [role, label] of [
    ['sans', 'Sans serif'],
    ['serif', 'Serif'],
    ['display', 'Display'],
    ['mono', 'Monospace'],
  ] as const) {
    const options = (byRole[role] ?? []).sort((a, b) => a.label.localeCompare(b.label));
    if (options.length) groups.push({ label, options });
  }
  return groups;
})();

/** The same list, flat, where a grouped control is not worth it. */
export const FONT_CHOICES = FONT_GROUPS.flatMap((group) => group.options);

/** A face's role, for anything that wants to sort or group by it. */
export const roleOf = (font: FontKey) => FONT_ROLES[font] ?? 'sans';
