import { ICONS, THREE_PLANS, img, logos, openDays, person } from './shared';
import { type PageTemplate, b, col, inDays, link } from './types';

/* ═══════════════════════════════════════════════════════════════════════════
   Ten page templates, one for each kind of site in Betheme's range — agency,
   restaurant, clinic, property, travel, event, magazine, product leasing,
   personal portfolio and a coming-soon page. Each has exactly one h1 (its
   hero, or the magazine's masthead) and uses only demo pictures, which the
   templates API adds to the media library when a template is used.
   ═══════════════════════════════════════════════════════════════════════════ */

const agency: PageTemplate = {
  id: 'agency',
  name: 'Agency',
  category: 'Business',
  description: 'A studio home page: work, services, process, team and a strong call to action.',
  image: img('interior-studio'),
  page: { title: 'Northfold Studio', excerpt: 'An independent studio for brands, websites and digital products — small senior teams, weekly releases.' },
  blocks: [
    b('hero', {
      variant: 'mediaBottomLeft',
      eyebrow: 'Independent design & build studio',
      title: 'Brands and products, made to be used',
      lede: 'Northfold is twelve designers and engineers who take ideas from a first sketch to something people use every day.',
      links: [link('Start a project', '/contact'), link('See the work', '#work', 'outline')],
      imageUrl: img('scene-dusk'),
      alt: 'Layered hills at dusk',
      height: 'tall',
      overlay: 'medium',
    }),
    b('logoWall', { eyebrow: 'Trusted by', title: 'Teams we have made things with', columns: 6, logos: logos(6) }),
    b('cardGrid', {
      variant: 'icons',
      eyebrow: 'What we do',
      title: 'Three disciplines, one team',
      columns: 3,
      cards: [
        { title: 'Brand identity', body: 'Names, logos and the rules that keep them consistent everywhere.', imageUrl: ICONS.bolt, href: '/contact', buttonLabel: 'Ask about branding' },
        { title: 'Websites', body: 'Fast, accessible sites your own team can edit without calling us.', imageUrl: ICONS.globe, href: '/contact', buttonLabel: 'Ask about websites' },
        { title: 'Product design', body: 'Apps and tools designed with the people who will use them.', imageUrl: ICONS.chart, href: '/contact', buttonLabel: 'Ask about products' },
      ],
    }),
    b('projects', {
      eyebrow: 'Selected work',
      title: 'Recent projects',
      layout: 'overlay',
      filter: false,
      items: [
        { title: 'Tidewater pavilion', category: 'Identity', year: '2026', summary: 'Signage and a visitor site for a harbour pavilion.', imageUrl: img('arch-pavilion'), alt: 'A low pavilion among trees', href: '/contact' },
        { title: 'Lumen lamp', category: 'Product', year: '2025', summary: 'Launch site and packaging for a one-dial lamp.', imageUrl: img('product-lamp'), alt: 'A desk lamp casting warm light', href: '/contact' },
        { title: 'Grain & Co workshop', category: 'Website', year: '2025', summary: 'A booking site for a shared makers’ workshop.', imageUrl: img('interior-workshop'), alt: 'A workshop with a long bench', href: '/contact' },
      ],
    }),
    b('numberedList', {
      variant: 'steps',
      eyebrow: 'How it works',
      title: 'From first call to launch',
      items: [
        { title: 'Talk', body: 'A free call to understand what you need and whether we are the right fit.' },
        { title: 'Plan', body: 'A short written plan with a fixed date, a budget and what is out of scope.' },
        { title: 'Make', body: 'Weekly releases you can click, with a senior person on every call.' },
        { title: 'Hand over', body: 'Everything in your accounts, documented, with support for the first months.' },
      ],
    }),
    b('stats', {
      variant: 'counters',
      title: 'Twelve years in numbers',
      items: [
        { value: '180', unit: '+', label: 'Projects launched' },
        { value: '12', label: 'People, all senior' },
        { value: '94', unit: '%', label: 'Clients who return' },
        { value: '4.9', unit: '/5', label: 'Average rating' },
      ],
    }),
    b('quote', {
      eyebrow: 'Client story',
      quote: 'They gave us a brand our staff are proud of and a website we update ourselves. Nothing got lost between design and build.',
      name: 'Ana Ferreira',
      role: 'Director, Tidewater Trust',
      avatarUrl: person(5),
      imageUrl: img('arch-pavilion'),
      alt: 'The Tidewater pavilion',
    }),
    b('team', {
      eyebrow: 'The studio',
      title: 'The people you will work with',
      columns: 4,
      members: [
        { name: 'Jonas Weir', role: 'Founder, design', bio: 'Has named more companies than he can remember.', imageUrl: person(1) },
        { name: 'Clara Holm', role: 'Brand lead', bio: 'Builds identities that survive their tenth use.', imageUrl: person(2) },
        { name: 'Ruth Adeyemi', role: 'Engineering lead', bio: 'Makes websites load before you blink.', imageUrl: person(3) },
        { name: 'Dev Patel', role: 'Product designer', bio: 'Sits in on user calls so nobody else has to guess.', imageUrl: person(4) },
      ],
    }),
    b('cta', { variant: 'big', eyebrow: 'Have a project in mind?', title: 'Tell us about it — we reply within a day', links: [link('Start a project', '/contact')] }),
  ],
};

const restaurant: PageTemplate = {
  id: 'restaurant',
  name: 'Restaurant',
  category: 'Food and drink',
  description: 'A menu with prices, opening hours that say whether you are open now, reviews, a map and table booking.',
  image: img('interior-lounge'),
  page: { title: 'Harbour Table', excerpt: 'Seasonal cooking by the harbour — lunch and dinner from Wednesday to Sunday. Book a table online.' },
  blocks: [
    b('hero', {
      variant: 'mediaCenter',
      eyebrow: 'Seasonal kitchen · Wednesday to Sunday',
      title: 'Cooking with what the boats and farms bring in',
      lede: 'A small dining room by the harbour, a menu that changes every week, and a long table for friends.',
      links: [link('Book a table', '#book'), link('See the menu', '#menu', 'outline')],
      imageUrl: img('interior-lounge'),
      alt: 'A warm dining room in the evening',
      height: 'tall',
      overlay: 'strong',
    }),
    b('splitMedia', {
      eyebrow: 'Our kitchen',
      title: 'Short menu, long lunches',
      body: 'We write the menu on Tuesday, after the market. Fish comes from two boats in the harbour, vegetables from farms within an hour of the door.\n\nThe bread is baked in the morning and the dessert is whatever the fruit says it should be.',
      imageUrl: img('interior-workshop'),
      alt: 'The kitchen pass in daylight',
      shape: 'organic',
    }),
    b('priceList', {
      eyebrow: 'This week',
      title: 'The menu',
      intro: 'Changes every week. Ask us about allergens — the kitchen knows every ingredient.',
      layout: 'columns',
      groups: [
        {
          title: 'To start',
          items: [
            { name: 'Harbour crab on toast', price: '€12', description: 'Brown butter, lemon and dill.' },
            { name: 'Charred leeks', price: '€9', description: 'Hazelnut dressing, soft egg.', tags: ['Vegetarian'] },
            { name: 'Cured mackerel', price: '€11', description: 'Pickled cucumber, horseradish cream.' },
          ],
        },
        {
          title: 'Mains',
          items: [
            { name: 'Catch of the day', price: '€26', badge: 'Popular', description: 'Whole or filleted, with greens and sea herbs.' },
            { name: 'Slow lamb shoulder', price: '€28', description: 'White beans, salsa verde.' },
            { name: 'Squash and barley', price: '€19', description: 'Sage, aged cheese, crisp onions.', tags: ['Vegetarian'] },
          ],
        },
        {
          title: 'Afters',
          items: [
            { name: 'Burnt honey tart', price: '€8', description: 'Crème fraîche.' },
            { name: 'Poached pears', price: '€8', description: 'Spiced syrup, oat crumble.', tags: ['Vegan'] },
          ],
        },
        {
          title: 'To drink',
          note: 'Wines by the glass change with the menu.',
          items: [
            { name: 'House white or red', price: '€7', description: 'By the glass.' },
            { name: 'Harbour lemonade', price: '€4', description: 'Pressed every morning.' },
          ],
        },
      ],
      footnote: 'A 10% service charge is added for tables of six or more.',
    }),
    b('gallery', {
      eyebrow: 'The room',
      title: 'Come and sit with us',
      captions: 'below',
      images: [
        { url: img('interior-lounge'), alt: 'The dining room at night', caption: 'The dining room' },
        { url: img('product-bottle'), alt: 'A bottle with a paper label', caption: 'Our own lemonade' },
        { url: img('scene-ocean'), alt: 'Headlands over the sea', caption: 'The view at lunch' },
        { url: img('interior-studio'), alt: 'A bright room with a long table', caption: 'The long table' },
        { url: img('product-lamp'), alt: 'A warm lamp', caption: 'After dark' },
        { url: img('scene-dusk'), alt: 'Hills at dusk', caption: 'Summer evenings' },
      ],
    }),
    b('reviews', {
      eyebrow: 'Reviews',
      title: 'What guests say',
      summary: { rating: 4.8, count: '312 reviews', label: 'from guests' },
      items: [
        { name: 'Lotte B.', rating: 5, title: 'The crab toast alone', text: 'We came for lunch and stayed until four. Warm, unfussy and every plate was excellent.', date: 'May 2026', source: 'Google' },
        { name: 'Marcus O.', rating: 5, text: 'Best fish we have had on this coast. Book ahead at weekends.', date: 'April 2026', source: 'Google' },
        { name: 'Inés R.', rating: 4.5, text: 'Lovely room and kind staff. The pear dessert was the surprise of the night.', date: 'April 2026', source: 'Tripadvisor' },
      ],
    }),
    b('businessHours', {
      eyebrow: 'Opening hours',
      title: 'When we are open',
      style: 'card',
      timeZone: 'Europe/Lisbon',
      week: [...openDays(['wed', 'thu', 'fri', 'sat'], '12:00', '23:00'), ...openDays(['sun'], '12:00', '17:00')],
      notes: [{ label: 'Kitchen', text: 'Last orders an hour before closing.' }],
    }),
    b('form', {
      eyebrow: 'Reservations',
      title: 'Book a table',
      intro: 'For tonight, please call us. For any other day, send this and we will confirm by email within a few hours.',
      formName: 'Table booking',
      layout: 'card',
      submitLabel: 'Request a table',
      successTitle: 'Thank you — we have your request.',
      successText: 'We will confirm by email shortly. If anything changes, just reply to that email.',
      fields: [
        { id: 'name', type: 'text', label: 'Name', required: true, width: 'half' },
        { id: 'email', type: 'email', label: 'Email', required: true, width: 'half' },
        { id: 'date', type: 'date', label: 'Date', required: true, width: 'half' },
        { id: 'time', type: 'select', label: 'Time', required: true, width: 'half', placeholder: 'Choose a time', options: ['12:30', '13:30', '19:00', '20:00', '21:00'] },
        { id: 'guests', type: 'select', label: 'Guests', required: true, width: 'half', placeholder: 'How many?', options: ['1', '2', '3', '4', '5', '6', '7', '8 or more'] },
        { id: 'phone', type: 'phone', label: 'Phone', width: 'half' },
        { id: 'notes', type: 'textarea', label: 'Anything we should know?', placeholder: 'Allergies, a birthday, a high chair…' },
      ],
    }),
    b('map', {
      eyebrow: 'Find us',
      title: 'On the harbour wall',
      layout: 'split',
      address: '4 Quay Street\nHarbourside',
      lat: 38.7071,
      lng: -9.1353,
      details: [
        { label: 'Phone', value: '+351 210 000 000' },
        { label: 'Parking', value: 'Public car park two minutes away' },
      ],
    }),
  ],
};

const clinic: PageTemplate = {
  id: 'clinic',
  name: 'Clinic',
  category: 'Health',
  description: 'A practice with services, a first-visit guide, the doctors, opening hours, reviews and appointment requests.',
  image: img('interior-studio'),
  page: { title: 'Larch Street Clinic', excerpt: 'Family doctors, physiotherapy and minor surgery under one roof. Same-week appointments, requested online.' },
  blocks: [
    b('hero', {
      variant: 'split',
      eyebrow: 'Family practice · since 2009',
      title: 'Unhurried care from doctors who know your name',
      lede: 'Family medicine, physiotherapy and minor procedures, with same-week appointments and time to talk.',
      links: [link('Request an appointment', '#appointment'), link('Our services', '#services', 'outline')],
      imageUrl: img('interior-studio'),
      alt: 'A bright consulting room',
    }),
    b('cardGrid', {
      variant: 'icons',
      eyebrow: 'Services',
      title: 'What we can help with',
      columns: 3,
      cards: [
        { title: 'Family medicine', body: 'Check-ups, long-term conditions and the questions you have been putting off.', imageUrl: ICONS.shield },
        { title: 'Physiotherapy', body: 'Back, joint and sports injuries, with a plan you can follow at home.', imageUrl: ICONS.leaf },
        { title: 'Minor procedures', body: 'Stitches, moles and small operations without a hospital visit.', imageUrl: ICONS.bolt },
        { title: 'Vaccinations', body: 'Travel, seasonal and childhood vaccinations, often on the same day.', imageUrl: ICONS.globe },
        { title: 'Health checks', body: 'A full check-up with blood tests and a follow-up conversation.', imageUrl: ICONS.chart },
        { title: 'Evening clinic', body: 'Appointments until eight on Tuesdays and Thursdays.', imageUrl: ICONS.clock },
      ],
    }),
    b('numberedList', {
      variant: 'steps',
      eyebrow: 'Your first visit',
      title: 'What to expect',
      items: [
        { title: 'Request a time', body: 'Use the form below or call us. We confirm within one working day.' },
        { title: 'Bring your details', body: 'Your ID, any medicines you take and letters from other doctors.' },
        { title: 'Take your time', body: 'First appointments last thirty minutes, so nothing is rushed.' },
        { title: 'Leave with a plan', body: 'A written summary and, if you need one, a follow-up booked there and then.' },
      ],
    }),
    b('team', {
      eyebrow: 'Our doctors',
      title: 'The team at Larch Street',
      columns: 3,
      members: [
        { name: 'Dr. Helena Voss', role: 'Family doctor', bio: 'Twenty years in family practice; special interest in heart health.', imageUrl: person(2) },
        { name: 'Dr. Samuel Ortiz', role: 'Family doctor', bio: 'Looks after children and teenagers, and runs the evening clinic.', imageUrl: person(1) },
        { name: 'Amira Khan', role: 'Physiotherapist', bio: 'Former sports physio who treats desk backs as seriously as marathons.', imageUrl: person(6) },
      ],
    }),
    b('row', {
      gap: '32px',
      align: 'stretch',
      columns: [
        col({ base: 6, tablet: 12 }, [
          b('businessHours', {
            title: 'Opening hours',
            style: 'card',
            timeZone: 'Europe/Berlin',
            week: [...openDays(['mon', 'wed', 'fri'], '08:00', '18:00'), ...openDays(['tue', 'thu'], '08:00', '20:00'), ...openDays(['sat'], '09:00', '12:00')],
            notes: [{ label: 'Out of hours', text: 'Call the regional line on 116 117.' }],
          }),
        ]),
        col({ base: 6, tablet: 12 }, [
          b('infoPanel', {
            title: 'Contact the clinic',
            items: [
              { label: 'Phone', value: '+49 30 0000 0000' },
              { label: 'Email', value: 'hello@larchstreet.example' },
              { label: 'Address', value: '18 Larch Street, ground floor, step-free' },
              { label: 'Insurance', value: 'All public and most private insurers' },
            ],
          }),
        ]),
      ],
    }),
    b('reviews', {
      eyebrow: 'Patients',
      title: 'What patients tell us',
      summary: { rating: 4.9, count: '540 reviews', label: 'from patients' },
      items: [
        { name: 'Paula M.', rating: 5, text: 'For the first time a doctor had time to listen. I left with a plan, not just a prescription.', date: 'June 2026', source: 'Google' },
        { name: 'Georg T.', rating: 5, text: 'Six sessions with Amira and I am running again. Clear exercises and honest advice.', date: 'May 2026', source: 'Google' },
        { name: 'Yuki S.', rating: 4.5, text: 'Easy to book, on time and very friendly with my kids.', date: 'April 2026', source: 'Jameda' },
      ],
    }),
    b('faq', {
      eyebrow: 'Questions',
      title: 'Before you come',
      items: [
        { question: 'Do I need to be registered to book?', answer: 'No. New patients are welcome; we register you at your first visit.' },
        { question: 'How soon can I be seen?', answer: 'Usually within the same week, and on the same day for urgent problems — call us in the morning.' },
        { question: 'Can I bring my children?', answer: 'Yes. Our family doctors see patients of every age, and there is space for a buggy in every room.' },
        { question: 'What if I need to cancel?', answer: 'Reply to your confirmation email or call us, ideally a day before, so someone else can have the time.' },
      ],
    }),
    b('form', {
      eyebrow: 'Appointments',
      title: 'Request an appointment',
      intro: 'This is a request, not a booking: we reply within one working day with a time. For an emergency, call 112.',
      formName: 'Appointment request',
      submitLabel: 'Send the request',
      successTitle: 'Thank you — your request is with us.',
      successText: 'We will reply within one working day with a time that suits you.',
      fields: [
        { id: 'name', type: 'text', label: 'Full name', required: true, width: 'half' },
        { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
        { id: 'email', type: 'email', label: 'Email', width: 'half' },
        { id: 'service', type: 'select', label: 'What is it about?', required: true, width: 'half', placeholder: 'Choose one', options: ['Family medicine', 'Physiotherapy', 'Minor procedure', 'Vaccination', 'Health check'] },
        { id: 'when', type: 'radio', label: 'Best time for you', options: ['Morning', 'Afternoon', 'Evening clinic'] },
        { id: 'date', type: 'date', label: 'Earliest date', width: 'half' },
        { id: 'message', type: 'textarea', label: 'Anything the doctor should know?', help: 'Keep it short — we will talk it through in person.' },
        { id: 'consent', type: 'consent', label: 'I agree to the clinic storing these details to arrange my appointment.', required: true },
      ],
    }),
  ],
};

const realEstate: PageTemplate = {
  id: 'real-estate',
  name: 'Real estate',
  category: 'Property',
  description: 'An estate agent with featured homes, figures, the agents, a valuation offer and a contact form.',
  image: img('arch-facade'),
  page: { title: 'Keyline Homes', excerpt: 'Homes to buy and rent across the city, and free valuations from agents who know every street.' },
  blocks: [
    b('hero', {
      variant: 'mediaBottomLeft',
      eyebrow: 'Buy · Rent · Sell',
      title: 'Find a home that fits the way you live',
      lede: 'Keyline agents know every street in the city. Tell us what matters and we will show you homes that match — before they reach the portals.',
      links: [link('See homes for sale', '#homes'), link('Book a valuation', '#valuation', 'outline')],
      imageUrl: img('arch-facade'),
      alt: 'A pale stone facade on a bright day',
      height: 'tall',
      overlay: 'medium',
    }),
    b('stats', {
      variant: 'counters',
      title: 'Keyline in numbers',
      items: [
        { value: '1,240', label: 'Homes sold' },
        { value: '19', label: 'Days to sell, on average' },
        { value: '98', unit: '%', label: 'Of asking price achieved' },
        { value: '4.9', unit: '/5', label: 'Seller rating' },
      ],
    }),
    b('cardGrid', {
      variant: 'imageCards',
      eyebrow: 'Featured homes',
      title: 'New this week',
      columns: 3,
      cards: [
        { title: 'Garden flat, Riverside', body: '2 bedrooms · 78 m² · €412,000', imageUrl: img('interior-lounge'), alt: 'A warm living room', href: '/contact', buttonLabel: 'Arrange a viewing' },
        { title: 'Loft, Old Town', body: '1 bedroom · 64 m² · €1,650 a month', imageUrl: img('interior-studio'), alt: 'A bright open-plan room', href: '/contact', buttonLabel: 'Arrange a viewing' },
        { title: 'Family house, Parkside', body: '4 bedrooms · 162 m² · €789,000', imageUrl: img('arch-pavilion'), alt: 'A low house among trees', href: '/contact', buttonLabel: 'Arrange a viewing' },
      ],
    }),
    b('splitMedia', {
      eyebrow: 'Selling with us',
      title: 'A valuation you can trust, a sale you can plan',
      body: 'We value from real sales on your street, not a formula. Then we plan photos, viewings and the price with you, and call you after every viewing.\n\nNo sale, no fee — and you can leave with two weeks’ notice.',
      links: [link('Book a free valuation', '#valuation')],
      imageUrl: img('arch-tower'),
      alt: 'A city tower at dusk',
    }),
    b('checkLists', {
      title: 'What is included when you sell',
      lists: [
        { title: 'Before listing', items: ['A free valuation', 'Professional photos and floor plan', 'Advice on small repairs that pay off'] },
        { title: 'Until the keys change hands', items: ['Accompanied viewings', 'Feedback after every viewing', 'Help with offers and paperwork'] },
      ],
    }),
    b('team', {
      eyebrow: 'Agents',
      title: 'Your local team',
      columns: 4,
      members: [
        { name: 'Olivia Brandt', role: 'Sales, Riverside', imageUrl: person(5) },
        { name: 'Karim Haddad', role: 'Lettings, Old Town', imageUrl: person(4) },
        { name: 'Sofia Lind', role: 'Sales, Parkside', imageUrl: person(3) },
        { name: 'Ben Carter', role: 'Valuations', imageUrl: person(1) },
      ],
    }),
    b('quote', {
      eyebrow: 'Sellers',
      quote: 'Two viewings, three offers and a sale above the asking price. They called after every step.',
      name: 'Hugo and Mette',
      role: 'Sold in Parkside',
      avatarUrl: person(2),
    }),
    b('contactForm', {
      layout: 'split',
      eyebrow: 'Valuations',
      title: 'Book a free valuation',
      intro: 'Tell us the address and a good time to call. It takes forty minutes and there is no obligation.',
      imageUrl: img('interior-lounge'),
      alt: 'A sunny living room',
    }),
  ],
};

const travel: PageTemplate = {
  id: 'travel',
  name: 'Travel guide',
  category: 'Travel',
  description: 'A destination guide with places to go, a day-by-day route, a photo gallery, reviews and a newsletter.',
  image: img('scene-ocean'),
  page: { title: 'Slow Roads — the coast in five days', excerpt: 'A five-day route along the coast: where to walk, eat and stay, with maps and tips from people who live there.' },
  blocks: [
    b('hero', {
      variant: 'mediaCenter',
      eyebrow: 'Travel guide · 5 days',
      title: 'The coast road, taken slowly',
      lede: 'Headlands, fishing villages and long lunches — a five-day route for people who would rather stop than rush.',
      links: [link('See the route', '#route'), link('Get the newsletter', '#newsletter', 'outline')],
      imageUrl: img('scene-ocean'),
      alt: 'Headlands over a calm sea',
      height: 'tall',
      overlay: 'medium',
    }),
    b('cardGrid', {
      variant: 'imageCards',
      eyebrow: 'Where to go',
      title: 'Four places worth the detour',
      columns: 4,
      cards: [
        { title: 'The headlands', body: 'Cliff paths with the best sunsets on the coast.', imageUrl: img('scene-dusk'), alt: 'Hills at dusk' },
        { title: 'Pine valley', body: 'Shade, streams and a picnic spot locals keep quiet.', imageUrl: img('scene-forest'), alt: 'Green hills in mist' },
        { title: 'The dunes', body: 'Sand as far as you can see, best at first light.', imageUrl: img('scene-desert'), alt: 'Warm dunes under a pale sun' },
        { title: 'Dark-sky ridge', body: 'No towns for miles — bring a blanket and stay late.', imageUrl: img('scene-night'), alt: 'A starry sky over ridges' },
      ],
    }),
    b('numberedList', {
      variant: 'timeline',
      eyebrow: 'The route',
      title: 'Day by day',
      items: [
        { title: 'Day 1 — Arrive at the harbour', body: 'Settle in, walk the harbour wall and eat whatever came in on the boats.' },
        { title: 'Day 2 — The headland path', body: 'Twelve kilometres of cliff path, ending at a café with a view.' },
        { title: 'Day 3 — Into the valley', body: 'A gentle inland loop through pine woods, with a swim in the river.' },
        { title: 'Day 4 — The dunes at dawn', body: 'An early start for the light, then a slow afternoon in the village.' },
        { title: 'Day 5 — Stars on the ridge', body: 'Drive up after dinner for the darkest sky on the coast.' },
      ],
    }),
    b('gallery', {
      eyebrow: 'Photos',
      title: 'Along the way',
      layout: 'masonry',
      columns: 3,
      captions: 'overlay',
      images: [
        { url: img('scene-ocean'), alt: 'The sea at midday', caption: 'Midday at the point' },
        { url: img('scene-dawn'), alt: 'Hills at dawn', caption: 'First light' },
        { url: img('arch-pavilion'), alt: 'A pavilion among trees', caption: 'The valley café' },
        { url: img('scene-forest'), alt: 'Misty green hills', caption: 'Pine valley' },
        { url: img('scene-desert'), alt: 'Dunes', caption: 'The dunes' },
        { url: img('scene-night'), alt: 'Stars over ridges', caption: 'Dark-sky ridge' },
      ],
    }),
    b('checkLists', {
      title: 'Before you go',
      lists: [
        { title: 'Pack', items: ['Walking shoes that are already broken in', 'A light rain jacket, even in summer', 'A head torch for the ridge'] },
        { title: 'Know', items: ['Most villages close by nine in the evening', 'Buses run twice a day off-season', 'Cash is still welcome in the markets'] },
      ],
    }),
    b('reviews', {
      eyebrow: 'Travellers',
      title: 'People who took the route',
      summary: { rating: 4.9, count: '88 reviews', label: 'from readers' },
      items: [
        { name: 'Emma & Joe', rating: 5, text: 'We followed it to the letter and still found our own favourite spots. Day four was magic.', date: 'May 2026' },
        { name: 'Farid A.', rating: 5, text: 'Honest tips, no sponsored nonsense. The valley swim was the highlight.', date: 'April 2026' },
        { name: 'Grete L.', rating: 4.5, text: 'Perfect pace for a family with teenagers.', date: 'March 2026' },
      ],
    }),
    b('newsletter', {
      layout: 'centered',
      fieldStyle: 'underline',
      eyebrow: 'Newsletter',
      title: 'One slow route a month',
      body: 'A new route every month, written by people who live there. No adverts, ever.',
    }),
  ],
};

const event: PageTemplate = {
  id: 'event',
  name: 'Event',
  category: 'Events',
  description: 'A conference page with a countdown, the schedule, speakers, tickets, questions and the venue.',
  image: img('scene-night'),
  page: { title: 'Signal — a day about small teams', excerpt: 'One day of talks and workshops about building good things with small teams. Tickets on sale now.' },
  blocks: [
    b('hero', {
      variant: 'statementFrame',
      eyebrow: 'One day · Twelve talks · 400 people',
      title: 'Signal — a day about small teams doing big things',
      lede: 'Talks, workshops and long lunches with the people behind products you use every day.',
      links: [link('Get a ticket', '#tickets'), link('See the schedule', '#schedule', 'outline')],
      imageUrl: img('scene-night'),
      alt: 'A starry sky over dark ridges',
    }),
    b('countdown', { eyebrow: 'Doors open in', title: 'Until Signal begins', target: inDays(60), style: 'boxed', dividers: true, expiredText: 'Signal is on — see you inside.' }),
    b('numberedList', {
      variant: 'timeline',
      eyebrow: 'Schedule',
      title: 'The day',
      items: [
        { title: '09:00 — Doors and coffee', body: 'Pick up your badge, find a seat, meet the people next to you.' },
        { title: '09:45 — Opening talk', body: '“Ten people, one product, no managers”: how a small team outgrew its plan.' },
        { title: '11:00 — Workshops', body: 'Four rooms, ninety minutes each: research, design systems, pricing, hiring.' },
        { title: '13:00 — Long lunch', body: 'Tables by topic, so you eat with people who share your problems.' },
        { title: '14:30 — Afternoon talks', body: 'Six short talks, each followed by questions from the floor.' },
        { title: '18:00 — Drinks', body: 'On the terrace, until the last speaker leaves.' },
      ],
    }),
    b('team', {
      eyebrow: 'Speakers',
      title: 'Who is talking',
      columns: 4,
      variant: 'overlay',
      members: [
        { name: 'Noor Haddad', role: 'Founder, Tidepool', bio: 'Built a product used by a million people with nine colleagues.', imageUrl: person(3) },
        { name: 'Leo Marchetti', role: 'Design lead, Arc', bio: 'Runs the design system behind forty apps.', imageUrl: person(1) },
        { name: 'Ada Nwosu', role: 'Engineer, Fieldnote', bio: 'Writes about shipping every day without breaking things.', imageUrl: person(5) },
        { name: 'Tomas Berg', role: 'Researcher, Kiln', bio: 'Has interviewed two thousand customers and still enjoys it.', imageUrl: person(4) },
      ],
    }),
    b('pricing', {
      eyebrow: 'Tickets',
      title: 'Choose a ticket',
      intro: 'Every ticket includes lunch, coffee and the evening drinks.',
      plans: [
        { name: 'Standard', tagline: 'The whole day', price: '€290', description: 'Talks, lunch and drinks.', features: [{ text: 'All talks', included: true }, { text: 'Lunch and drinks', included: true }, { text: 'Workshops', included: false }], button: { label: 'Buy Standard', href: '/contact' } },
        { name: 'Full', tagline: 'Talks and a workshop', price: '€390', badge: 'Best value', featured: true, description: 'Everything, plus a workshop seat.', features: [{ text: 'All talks', included: true }, { text: 'Lunch and drinks', included: true }, { text: 'One workshop', included: true }], button: { label: 'Buy Full', href: '/contact' } },
        { name: 'Team of five', tagline: 'Come together', price: '€1,650', description: 'Five Full tickets, one invoice.', features: [{ text: 'Five Full tickets', included: true }, { text: 'Reserved table at lunch', included: true }, { text: 'One invoice', included: true }], button: { label: 'Buy for a team', href: '/contact' } },
      ],
      footnote: 'Prices include VAT. Tickets can be transferred to a colleague at any time.',
    }),
    b('faq', {
      eyebrow: 'Questions',
      title: 'Good to know',
      items: [
        { question: 'Will the talks be recorded?', answer: 'Yes. Every ticket holder gets the recordings two weeks after the day.' },
        { question: 'Is the venue accessible?', answer: 'Fully step-free, with a quiet room and live captions in the main hall.' },
        { question: 'Can I get a refund?', answer: 'Up to thirty days before the day. After that you can pass your ticket to someone else.' },
      ],
    }),
    b('map', {
      eyebrow: 'Venue',
      title: 'The Old Tram Depot',
      layout: 'split',
      address: '2 Depot Yard\nCity centre',
      lat: 52.3731,
      lng: 4.8922,
      details: [
        { label: 'Getting there', value: 'Five minutes from the central station on foot' },
        { label: 'Hotels', value: 'Ticket holders get 15% off at three partner hotels' },
      ],
    }),
    b('cta', { variant: 'big', eyebrow: 'Only 400 places', title: 'Get your ticket before they are gone', links: [link('Buy a ticket', '#tickets')] }),
  ],
};

const magazine: PageTemplate = {
  id: 'magazine',
  name: 'Magazine',
  category: 'Media',
  description: 'A news front page: a masthead, one big story with a list beside it, news cards, a newsletter and more reading.',
  image: img('ui-analytics'),
  page: { title: 'The Field Notes', excerpt: 'Weekly stories about work, design and the people who make things — independent and reader-funded.' },
  blocks: [
    b('heading', {
      size: 'display',
      align: 'center',
      titleAs: 'h1',
      eyebrow: 'Independent · Reader-funded · Weekly',
      title: 'The Field Notes',
      subtitle: 'Stories about work, design and the people who make things.',
    }),
    b('postList', { variant: 'featured', eyebrow: 'This week', title: 'Top stories', limit: 5 }),
    b('postList', { variant: 'news', eyebrow: 'Latest', title: 'Just published', limit: 3 }),
    b('newsletter', {
      layout: 'centered',
      eyebrow: 'Every Friday',
      title: 'The week’s best reading, in one email',
      body: 'Five stories, chosen by the editors. Free, and easy to leave.',
    }),
    b('postList', { variant: 'compact', eyebrow: 'From the archive', title: 'Worth another read', limit: 6 }),
    b('cta', {
      variant: 'inline',
      tone: 'raised',
      title: 'Support independent writing',
      body: 'The Field Notes has no adverts. Readers pay for it — and get every story first.',
      links: [link('Become a member', '/contact')],
    }),
  ],
};

const leasing: PageTemplate = {
  id: 'leasing',
  name: 'Product leasing',
  category: 'Product',
  description: 'A product page for leasing a device: benefits, what is included, monthly plans with a yearly switch and questions.',
  image: img('product-graphite'),
  page: { title: 'Loop — lease the device, not the worry', excerpt: 'Lease the latest device for a fixed monthly price, with repairs, insurance and an upgrade every two years.' },
  blocks: [
    b('hero', {
      variant: 'split',
      eyebrow: 'Lease from €19 a month',
      title: 'The latest device, without the price tag',
      lede: 'One fixed monthly price with repairs, insurance and an upgrade every two years. Return it whenever you like after the first year.',
      links: [link('See the plans', '#plans'), link('How leasing works', '#how', 'outline')],
      imageUrl: img('product-graphite'),
      alt: 'A handheld device in graphite',
    }),
    b('logoWall', { eyebrow: 'Used at work by', title: 'Teams that lease with Loop', columns: 6, logos: logos(6) }),
    b('tabs', {
      eyebrow: 'Why lease',
      title: 'Better than buying, for most people',
      tabs: [
        { label: 'Always new', title: 'An upgrade every two years', body: 'Swap for the newest model every two years at no extra cost. We collect the old one.', imageUrl: img('product-ocean'), alt: 'A device in ocean blue' },
        { label: 'No surprises', title: 'Repairs and insurance included', body: 'Cracked screen, flat battery, lost in a taxi — it is covered, with a replacement in two days.', imageUrl: img('product-ruby'), alt: 'A device in ruby red' },
        { label: 'For teams', title: 'One invoice for everyone', body: 'Add people in a minute, see every device in one place, and pay one monthly bill.', imageUrl: img('ui-dashboard'), alt: 'A fleet dashboard' },
      ],
    }),
    b('checkLists', {
      title: 'What every lease includes',
      lists: [
        { title: 'Always', items: ['The device, set up and ready', 'Accident and theft insurance', 'Free repairs and a loan device', 'An upgrade every two years'] },
        { title: 'Teams also get', items: ['A dashboard for every device', 'Remote lock and wipe', 'A named contact', 'Monthly invoicing'] },
      ],
    }),
    b('pricing', {
      eyebrow: 'Plans',
      title: 'Pick a plan, change it any time',
      intro: 'Pay yearly and save a fifth.',
      billing: 'switch',
      yearlyNote: 'Save 20%',
      plans: THREE_PLANS.map((plan, i) => ({ ...plan, name: ['Lite', 'Standard', 'Pro'][i]!, description: ['The 128 GB model.', 'The 256 GB model with the better camera.', 'The 1 TB model with every extra.'][i]!, button: { label: `Lease ${['Lite', 'Standard', 'Pro'][i]!}`, href: '/contact' } })),
      footnote: 'Minimum term twelve months. Prices include VAT.',
    }),
    b('stats', {
      variant: 'counters',
      title: 'Leasing with Loop',
      items: [
        { value: '48', unit: 'h', label: 'Replacement time' },
        { value: '60,000', label: 'Devices leased' },
        { value: '92', unit: '%', label: 'Renew after two years' },
      ],
    }),
    b('faq', {
      eyebrow: 'Questions',
      title: 'Leasing, explained',
      items: [
        { question: 'Do I ever own the device?', answer: 'No — and that is the point: you never have to sell or recycle it. You can buy it at the end if you want.' },
        { question: 'What if I break it?', answer: 'Tell us in the app. We send a replacement within two working days and collect the broken one.' },
        { question: 'Can I cancel?', answer: 'After the first twelve months, with one month’s notice. Send the device back in the box we provide.' },
        { question: 'Is there a credit check?', answer: 'A light one, which does not affect your credit score.' },
      ],
    }),
    b('cta', { variant: 'big', eyebrow: 'Ready when you are', title: 'Lease yours today — delivered tomorrow', links: [link('Choose a plan', '#plans')] }),
  ],
};

const portfolio: PageTemplate = {
  id: 'portfolio',
  name: 'Personal portfolio',
  category: 'Personal',
  description: 'A designer’s one-page portfolio: an introduction, selected work, skills, a client quote and a contact form.',
  image: img('person-2'),
  page: { title: 'Ines Marlow — product designer', excerpt: 'Independent product designer helping small teams make tools that are calm, clear and quick to learn.' },
  blocks: [
    b('hero', {
      variant: 'split',
      eyebrow: 'Independent product designer',
      title: 'Hi, I’m Ines. I design calm, clear software.',
      lede: 'For ten years I have helped small teams turn complicated tools into ones people learn in an afternoon. Currently booking projects for next quarter.',
      links: [link('See my work', '#work'), link('Get in touch', '#contact', 'outline')],
      imageUrl: img('person-2'),
      alt: 'Portrait of Ines',
    }),
    b('projects', {
      eyebrow: 'Selected work',
      title: 'Recent projects',
      layout: 'minimal',
      items: [
        { title: 'Fieldnote', category: 'Product', year: '2026', summary: 'A research tool that turned interviews into answers.', imageUrl: img('ui-analytics'), alt: 'A reporting screen', href: '/contact' },
        { title: 'Kiln mobile', category: 'Mobile', year: '2025', summary: 'A booking app for a chain of pottery studios.', imageUrl: img('phone-home'), alt: 'A phone app home screen', href: '/contact' },
        { title: 'Tidepool', category: 'Product', year: '2025', summary: 'A dashboard nurses actually asked to keep.', imageUrl: img('ui-dashboard'), alt: 'An analytics dashboard', href: '/contact' },
        { title: 'Lumen', category: 'Brand', year: '2024', summary: 'Packaging and launch site for a one-dial lamp.', imageUrl: img('product-lamp'), alt: 'A desk lamp', href: '/contact' },
      ],
    }),
    b('checkLists', {
      eyebrow: 'What I do',
      title: 'Ways I can help',
      layout: 'grid',
      lists: [
        { title: 'Product design', items: ['Research and interviews', 'Flows and prototypes', 'Interface design'] },
        { title: 'Design systems', items: ['Audits of what you have', 'Components and guidelines', 'Handover to engineers'] },
        { title: 'Workshops', items: ['Kick-off and discovery', 'Prioritising a roadmap', 'Usability testing'] },
      ],
    }),
    b('quote', {
      eyebrow: 'Kind words',
      quote: 'Ines asked the questions we had been avoiding for a year. The product is simpler, and our support tickets halved.',
      name: 'Noor Haddad',
      role: 'Founder, Tidepool',
      avatarUrl: person(3),
    }),
    b('socialLinks', { title: 'Elsewhere', source: 'site', style: 'outlined' }),
    b('contactForm', {
      layout: 'centered',
      eyebrow: 'Contact',
      title: 'Have a project in mind?',
      intro: 'Tell me a little about it. I reply to every message within two days.',
    }),
  ],
};

const comingSoon: PageTemplate = {
  id: 'coming-soon',
  name: 'Coming soon',
  category: 'Launch',
  description: 'A launch page: a big statement, a countdown, a sign-up for the opening and social links.',
  image: img('scene-dawn'),
  page: { title: 'Opening soon', excerpt: 'Something new is on its way. Leave your email and be the first to know when the doors open.' },
  blocks: [
    b('hero', {
      variant: 'statementFrame',
      eyebrow: 'Opening soon',
      title: 'Something new is on its way',
      lede: 'We are putting the finishing touches to it. Leave your email and you will be the first to know.',
      links: [link('Tell me when', '#notify')],
      imageUrl: img('scene-dawn'),
      alt: 'Hills at dawn under a pink sky',
    }),
    b('countdown', { title: 'Opening in', target: inDays(30), style: 'boxed', dividers: true, align: 'center', expiredText: 'We are open — come in.' }),
    b('newsletter', {
      layout: 'centered',
      fieldStyle: 'underline',
      eyebrow: 'Be the first to know',
      title: 'One email on opening day',
      body: 'No other mail, and we delete the list after launch.',
    }),
    b('socialLinks', { title: 'Follow the build', source: 'site', style: 'filled' }),
  ],
};

/* ── Package 4: pages a slider carries ────────────────────────────────────── */

const productMicrosite: PageTemplate = {
  id: 'product-microsite',
  name: 'Product microsite',
  category: 'Product',
  description: 'A single product carried by sliders: a layered opening, a split screen of the making, a gallery and the specifications.',
  image: img('product-graphite'),
  page: { title: 'Pocket One', excerpt: 'One device, made to be repaired — the story, the specifications and where to buy it.' },
  blocks: [
    b('hero', {
      variant: 'layered',
      eyebrow: 'Pocket One',
      title: 'Small enough to forget, good enough to keep',
      lede: 'Eight years of battery life, a screen you can read in sunlight, and parts you can replace with a screwdriver.',
      links: [link('Buy from €499', '/contact'), link('See the specifications', '#specs', 'outline')],
      imageUrl: img('scene-dusk'),
      alt: 'Layered mountains at dusk',
      overlay: 'strong',
      pointerParallax: true,
      scrollCue: true,
      layers: [
        { imageUrl: img('product-graphite'), alt: 'The device in graphite', depth: 'back' },
        { imageUrl: img('product-ocean'), alt: 'The device in ocean blue', depth: 'middle' },
        { imageUrl: img('product-sand'), alt: 'The device in sand', depth: 'front' },
      ],
    }),
    b('carousel', {
      mode: 'splitScreen',
      kenBurns: true,
      indicator: 'none',
      slides: [
        {
          eyebrow: '[ 01 ]',
          title: 'Drawn by hand first',
          body: 'Every shape starts on paper, where a bad idea costs nothing.',
          imageUrl: img('interior-studio'),
          alt: 'A bright studio',
          href: '/contact',
          buttonLabel: 'Talk to us',
        },
        {
          eyebrow: '[ 02 ]',
          title: 'Built on a bench, not a line',
          body: 'Assembled in small runs so a fault never reaches a thousand people.',
          imageUrl: img('interior-workshop'),
          alt: 'A workshop bench in daylight',
          href: '/contact',
          buttonLabel: 'Talk to us',
        },
        {
          eyebrow: '[ 03 ]',
          title: 'Made to be opened',
          body: 'Standard screws, a published parts list and a repair guide for every model.',
          imageUrl: img('product-watch'),
          alt: 'A wristwatch with a dark dial',
          href: '/contact',
          buttonLabel: 'Talk to us',
        },
      ],
    }),
    b('carousel', {
      mode: 'filmstrip',
      eyebrow: 'Finishes',
      title: 'Four colours, all anodised in-house',
      intro: 'Click any frame to bring it forward.',
      indicator: 'counter',
      arrows: 'corner',
      slides: [
        { title: 'Graphite', imageUrl: img('product-graphite'), alt: 'The device in graphite' },
        { title: 'Sand', imageUrl: img('product-sand'), alt: 'The device in sand' },
        { title: 'Ocean', imageUrl: img('product-ocean'), alt: 'The device in ocean blue' },
        { title: 'Ruby', imageUrl: img('product-ruby'), alt: 'The device in ruby red' },
      ],
    }),
    b('carousel', {
      mode: 'media',
      tone: 'raised',
      eyebrow: 'Specifications',
      title: 'What is inside it',
      intro: 'The numbers that matter, beside the part they belong to.',
      indicator: 'thumbs',
      arrows: 'side',
      kenBurns: true,
      link: { label: 'Ask a question', href: '/contact' },
      slides: [
        {
          title: 'The screen',
          caption: 'The screen — readable in direct sun',
          imageUrl: img('phone-home'),
          alt: 'A phone app home screen',
          specs: [
            { label: 'Size', value: '4.3 inches' },
            { label: 'Type', value: 'Reflective, no backlight' },
            { label: 'Glass', value: 'Replaceable' },
          ],
        },
        {
          title: 'The battery',
          caption: 'The battery — eight years, then swap it',
          imageUrl: img('product-speaker'),
          alt: 'A rounded speaker with a dotted grille',
          specs: [
            { label: 'Life', value: '8 years typical' },
            { label: 'Charge', value: 'USB-C, 90 minutes' },
            { label: 'Replacing it', value: 'Two screws' },
          ],
        },
        {
          title: 'The case',
          caption: 'The case — one piece of aluminium',
          imageUrl: img('product-graphite'),
          alt: 'The device in graphite',
          specs: [
            { label: 'Material', value: 'Recycled aluminium' },
            { label: 'Weight', value: '128 g' },
            { label: 'Water', value: 'Splash resistant' },
          ],
        },
      ],
    }),
    b('stats', {
      variant: 'counters',
      title: 'Pocket One in numbers',
      items: [
        { value: '8', unit: ' yrs', label: 'Battery life' },
        { value: '128', unit: ' g', label: 'Weight' },
        { value: '94', unit: '%', label: 'Recycled aluminium' },
        { value: '5', unit: ' yr', label: 'Warranty' },
      ],
    }),
    b('faq', {
      eyebrow: 'Questions',
      title: 'Before you buy',
      items: [
        { question: 'Can I really repair it myself?', answer: 'Yes. Every part is sold separately, with a guide, and opening it does not void the warranty.' },
        { question: 'How long are parts available?', answer: 'Ten years from the day a model stops being made.' },
        { question: 'What is in the box?', answer: 'The device, a cable, and the screwdriver that fits it.' },
      ],
    }),
    b('cta', { variant: 'big', eyebrow: 'Ready when you are', title: 'Order one, keep it for a decade', links: [link('Buy from €499', '/contact')] }),
  ],
};

const photography: PageTemplate = {
  id: 'photography',
  name: 'Photography portfolio',
  category: 'Personal',
  description: 'A photographer’s page: a statement opening, a drifting filmstrip, a draggable series and a masonry gallery.',
  image: img('scene-dawn'),
  page: { title: 'Ilse Bergman — photographer', excerpt: 'Landscape and interior photography, printed large. Commissions and print sales.' },
  blocks: [
    b('hero', {
      variant: 'statementFrame',
      eyebrow: 'Photographer · landscapes and interiors',
      title: 'Pictures that hold still long enough to be looked at',
      lede: 'Commissions, prints and long walks. Based on the coast, working anywhere.',
      links: [link('See the work', '#work'), link('Commission a shoot', '/contact', 'outline')],
      imageUrl: img('scene-dawn'),
      alt: 'Hills at dawn under a pink sky',
    }),
    b('carousel', {
      mode: 'filmstrip',
      eyebrow: 'Selected frames',
      title: 'Between frames',
      indicator: 'counter',
      arrows: 'corner',
      slides: [
        { title: 'First light', imageUrl: img('scene-dawn'), alt: 'Hills at dawn' },
        { title: 'The dunes', imageUrl: img('scene-desert'), alt: 'Warm dunes under a pale sun' },
        { title: 'Open water', imageUrl: img('scene-ocean'), alt: 'Waves on open water' },
        { title: 'Pine valley', imageUrl: img('scene-forest'), alt: 'Green hills fading into mist' },
        { title: 'Dark skies', imageUrl: img('scene-night'), alt: 'A starry sky over dark ridges' },
        { title: 'Last light', imageUrl: img('scene-dusk'), alt: 'Layered mountains at dusk' },
      ],
    }),
    b('carousel', {
      eyebrow: 'Series',
      title: 'Work in sets, not singles',
      intro: 'Pull the row sideways to see each series.',
      drag: true,
      indicator: 'counter',
      arrows: 'corner',
      slides: [
        { eyebrow: 'Series', title: 'Rooms in winter', body: 'Interiors shot on grey afternoons.', imageUrl: img('interior-lounge'), alt: 'A warm lounge in the evening', href: '/contact', buttonLabel: 'See the series' },
        { eyebrow: 'Series', title: 'The working coast', body: 'Harbours before the season starts.', imageUrl: img('scene-ocean'), alt: 'Headlands over a calm sea', href: '/contact', buttonLabel: 'See the series' },
        { eyebrow: 'Series', title: 'Makers', body: 'Portraits at the bench.', imageUrl: img('interior-workshop'), alt: 'A workshop bench in daylight', href: '/contact', buttonLabel: 'See the series' },
        { eyebrow: 'Series', title: 'Quiet buildings', body: 'Architecture without people.', imageUrl: img('arch-pavilion'), alt: 'Low buildings among trees', href: '/contact', buttonLabel: 'See the series' },
      ],
    }),
    b('gallery', {
      eyebrow: 'Prints',
      title: 'Available as prints',
      layout: 'masonry',
      columns: 3,
      captions: 'overlay',
      images: [
        { url: img('scene-dawn'), alt: 'Hills at dawn', caption: 'First light — edition of 25' },
        { url: img('arch-pavilion'), alt: 'Low buildings among trees', caption: 'Pavilion — edition of 15' },
        { url: img('scene-desert'), alt: 'Warm dunes', caption: 'Dunes — edition of 25' },
        { url: img('interior-studio'), alt: 'A bright studio', caption: 'Studio — edition of 10' },
        { url: img('scene-night'), alt: 'A starry sky', caption: 'Dark skies — edition of 25' },
        { url: img('scene-forest'), alt: 'Misty green hills', caption: 'Valley — edition of 15' },
      ],
    }),
    b('quote', {
      eyebrow: 'Commissions',
      quote: 'She spent two days walking the site before taking a single frame. It shows in every picture.',
      name: 'Ana Ferreira',
      role: 'Director, Tidewater Trust',
      avatarUrl: person(5),
    }),
    b('contactForm', {
      layout: 'centered',
      eyebrow: 'Contact',
      title: 'Commissions and print enquiries',
      intro: 'Tell me what you have in mind and roughly when. I reply within two days.',
    }),
  ],
};

export const PAGE_TEMPLATES: PageTemplate[] = [
  agency,
  restaurant,
  clinic,
  realEstate,
  travel,
  event,
  magazine,
  leasing,
  portfolio,
  comingSoon,
  productMicrosite,
  photography,
];
